NewsPort/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls'))
]

news/urls.py
from django.urls import path
from .views import PostsList, PostDetail

urlpatterns = [
    path('', PostsList.as_view()),
    path('<int:pk>', PostDetail.as_view()),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.authorUser.username

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        # ------суммарный рейтинг всех комментариев к статьям автора.---------
        posts = self.post_set.all()
        commentPostRat = 0
        for post in posts:
            commentPostRow = post.comment_set.all().aggregate(cpRating=Sum('rating'))
            commentPostRat += commentPostRow.get('cpRating')

        self.ratingAuthor = pRat * 3 + cRat + commentPostRat
        # -------------------------------

        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'

    TYPES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    categoryType = models.CharField(max_length=2, choices=TYPES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.title

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough}: {self.postThrough}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.commentUser.username}: {self.commentPost.title}: {self.text[0:15] + "..."}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/views.py
from time import timezone
from django.utils import timezone
from django.views.generic import ListView, DetailView
from .models import Post


class PostsList(ListView):
    model = Post
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'news/post.html'
    context_object_name = 'post'

news/templates/news/post.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет "Новость или статья - Заголовок..." -->
{% block title %}
    {{ post.get_categoryType_display }}: {{ post.title|truncatechars:10  }}
{% endblock title %}

<!-- В контенте на странице мы выводим саму Новость или статью,
 первичный ключ которого был передан в адрес -->
{% block content %}
    <h1 align="center">{{ post.title|Censor }}</h1>
    <hr>
    <p>{{ post.text|Censor }}</p>
    <h5 align="right">{{ post.dateCreation| date:'d-M-Y H:i' }}</h5>
{% endblock content %}

news/templates/news/posts.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет Новости, статьи -->
{% block title %}
    Новости, статьи
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    <h1 align="center" >Все новости и статьи:</h1>
    <h5 align="right">{{ time_now| date:'d-M-Y H:i' }}</h5>
    <hr>
    <p> (Всего новостей и статей: {{ posts|length }})</p>

    {% if posts %}
        <table class="table">
            <tr>
                <th scope="col"> Название</th>
                <th scope="col"><p align="justify"> Дата публикации</p></th>
                <th scope="col">Содержимое</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.title|truncatewords:8|truncatechars:50|Censor }}</td>
                    <td>{{ post.dateCreation| date:'d-M-Y H:i' }}</td>
                    <td>{{ post.text|truncatechars:50|Censor }}</td>
                </tr>
            {% endfor %}

        </table>

    {% else %}
        <h2>Новостей и статей нет!</h2>

    {% endif %}

{% endblock content %}

templates/layout/default.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
{% endblock title %}
</title>
</head>
<body>
{% include './parts/header.html' %}
<div class="container">
 {% block content %}
 {% endblock content %}
</div>

{% include './parts/footer.html' %}
</body>
</html>

templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
 <div class="container">
   <span class="text-muted">Place sticky footer content here.</span>
 </div>
</footer>

templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
       <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
       <li><a href="#" class="nav-link px-2 text-white">About</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Login</button>
       <button type="button" class="btn btn-warning">Sign-up</button>
     </div>
   </div>
 </div>
</header>